### ISSUE TITLE
electrical to optical conversion

### ISSUE THREAD

**Issue by ghost** [MansourM61/FSO-Simulator-MATLAB#2]
hi, I'm new in optics and FSO system and I'm using your code and sources to figure out the math for simulation in matlab but I'm having some problems and I appreciate if u can help me with these!
in your code (FSO_system.m) in first line of section 3 where u calculate Laser_Sim_Out variable we have this equation:
Laser_Sim_Out = DelP_Sim*(Signal_Sim_Out - Sig_Level);  % generate laser output (W)
this equation makes sense and I don't have problem with it, you are adding some DC values to your signal (Signal_Sim_Out - Sig_Level) then multiply it by DelP_Sim to convert it to optical power! the result as you comment is in Watt. but in the code we have 0 or 1 values for Signal_Sim_Out  and 0.5 for Sig_Level which leads to negative values in Laser_Sim_Out for all 0 bits in Signal_Sim_Out  which I can't understand what does negative values in Watt mean in optical signal! 
by the way it was a nice persian poem in the first of your thesis! :)
I have some other problems and I would ask them in other issues cause they are related to other part of the code! thank you in advance :))

**Comment by MansourM61** [comment]
Hi @mamadzol,
I edited the comment to avoid any ambiguity.
Thanks.
